services:
  app:
    build: .
    container_name: api-backend-nodejs
    restart: always
    ports:
      - "3002:3002"
    environment:
      DB_HOST: mysql-1d02e5f8-senati-dc0f.d.aivencloud.com
      DB_USER: avnadmin
      DB_PASSWORD: tu_contraseña_real_aiven
      DB_NAME: defaultdb
      DB_PORT: 17888
      PORT: 3002
      JWT_SECRET: super_clave_secreta_jwt
